# Start in fullscreen mode by default.
fs=yes

# Save video progress
save-position-on-quit=yes

# Normalizes audio
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'

#profile=high-quality
#profile=gpu-hq 
vo=gpu-next 
display-fps-override=60
hwdec=no
hwdec-codecs=none
interpolation=yes

gpu-api=auto
priority=high 
gpu-context=auto
hwdec=d3d11va-copy
profile=high-quality   
d3d11-adapter=NVIDIA  


deband=no
deband-iterations=1
deband-threshold=48
deband-range=16
deband-grain=32

temporal-dither=yes

# Uses a large seekable RAM cache even for local input.
cache=yes


# Display English subtitles if available.
slang=en, eng
vlang=en, eng

sub-blur=0.5
sub-scale=0.8
sub-margin-y=60
sub-color='#d6ffffff'
sub-font='Roboto'
sub-shadow-offset=5.0
sub-back-color='#00000000'
sub-border-color='#266a678c'
sub-shadow-color='#00000000'
blend-subtitles=yes
sub-ass-override=yes  

# Config copied from youtube
sub-visibility=yes
sub-auto=fuzzy
alang=en, eng
audio-file-auto=fuzzy
audio-pitch-correction = yes
audio-normalize-downmix=yes              

msg-color=yes # color log messages on terminal
term-osd-bar=yes # displays a progress bar on the terminal
cursor-autohide=1000 # autohides the cursor after 1s
