
# Start in fullscreen mode by default.
fs=yes

# Specify high quality video rendering preset (for --vo=gpu only)
# Can cause performance problems with some drivers and GPUs.
profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
video-sync=display-resample
#scale=ewa_lanczossharp
#cscale=ewa_lanczossharp


# Uses a large seekable RAM cache even for local input.
cache=yes
# cache-secs=300
# Uses extra large RAM cache (needs cache=yes to make it useful).
demuxer-max-bytes=1800M
demuxer-max-back-bytes=1200M


# Normalizes audio
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'



# ===== Terminal =====

msg-color=yes # color log messages on terminal
term-osd-bar=yes # displays a progress bar on the terminal
cursor-autohide=1000 # autohides the cursor after 1s

# ===== OSD =====

# Sets a custom font
# (comment out line if font change is undesired)
osd-font='Iosevka'





#...........................................................................................................................
# ===== Color Space =====
# target-trc=auto
# gamma-auto
# vf=format=colorlevels=full:colormatrix=auto
# video-output-levels=full

# ===== Dithering =====
dither-depth=auto
temporal-dither=yes
dither=fruit

# ===== Debanding =====
deband=yes # enabled by default
deband-iterations=4 # deband steps
deband-threshold=48 # deband strength
deband-range=16 # deband range
deband-grain=48 # dynamic grain: set to "0" if using the static grain shader

# ===== Subtitles =====
blend-subtitles=yes

# ===== Motion Interpolation =====
override-display-fps=60
video-sync=display-resample
interpolation=yes
tscale=oversample # smoothmotion

# ===== Anti-Ringing =====
scale-antiring=0.7 # luma upscale deringing
dscale-antiring=0.7 # luma downscale deringing
cscale-antiring=0.7 # chroma upscale deringing
#...........................................................................................................................




# Force video to lock on the display's refresh rate, and change video and audio
# speed to some degree to ensure synchronous playback - can cause problems
# with some drivers and desktop environments.
#video-sync=display-resample
#interpolation=yes
# Interpolation method
#tscale=bicubic

#THIS OPTION HAS NO EFFECT WITH "vo=gpu"
#Trade smoothness for performance (disables dynamic updates)
#interpolation-preserve=no

# Enable hardware decoding if available. Often, this does not work with all
# video outputs, but should work well with default settings on most systems.
# If performance or energy usage is an issue, forcing the vdpau or vaapi VOs
# may or may not help.
hwdec=auto

# Save video progress
save-position-on-quit=yes

# Display English subtitles if available.
slang=en

# Config copied from youtube
sub-visibility=yes
sub-auto=fuzzy
alang=eng
audio-file-auto=fuzzy
sub-font-size=50

#Forces showing subtitles while seeking through the video
demuxer-mkv-subtitle-preroll=yes

#THIS OPTION HAS NO EFFECT WITH "vo=gpu-next"
#Subtitle blending in scenechanges (smoother effect)
#This is recommended if you use Interpolation
#Use "video" if you want to render it to video resolution instead, this will display typeset more accurate, but for the cost of sharpness
#blend-subtitles=yes
